// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EntityLibraryCore.Models
{
    public partial class GenderTypes
    {
        public GenderTypes()
        {
            Person = new HashSet<Person>();
        }

        [Key]
        public int GenderIdentifier { get; set; }
        public string Gender { get; set; }

        [InverseProperty("GenderIdentifierNavigation")]
        public virtual ICollection<Person> Person { get; set; }
    }
}