// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EntityLibraryCore.Models
{
    public partial class Person
    {
        [Key]
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? GenderIdentifier { get; set; }
        public bool? IsDeleted { get; set; }

        [ForeignKey(nameof(GenderIdentifier))]
        [InverseProperty(nameof(GenderTypes.Person))]
        public virtual GenderTypes GenderIdentifierNavigation { get; set; }

        public override string ToString() => $"{id} {FirstName} {LastName}";

    }
}